load("@rules_scala_annex//rules:scala.bzl", "scala_library")
load("@rules_scala_annex//rules:scala.bzl", "scala_binary")

scala_binary(
  name = "example",
  main_class = "example.Example",
  srcs = glob(["**/*.scala"])
)

